-- Superseded by dreamboard-core-schema.sql.
--
-- Community, Shop, Radio, creator timeline, and private storage policies now
-- live in the single Dreamboard core migration. Keeping one source of truth
-- prevents a second, conflicting set of community tables from being created.
