-- Superseded by dreamboard-core-schema.sql.
--
-- The live Dreamboard project uses public.wm_id as the canonical WM identity
-- and public.dreamboard_profiles for private creator preferences. Run only
-- dreamboard-core-schema.sql for a fresh Dreamboard setup.
